# Generated by Django 4.2.26 on 2025-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='trust_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='technician_photos/'),
        ),
    ]
