# Generated by Django 4.2.26 on 2025-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_technicianprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicianprofile',
            old_name='id_back',
            new_name='id_back_photo',
        ),
        migrations.RenameField(
            model_name='technicianprofile',
            old_name='id_front',
            new_name='id_front_photo',
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='active_jobs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='cancelled_jobs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='is_available_for_jobs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='pending_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='selfie_with_id',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='profile_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
