# Generated by Django 4.2.26 on 2025-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0004_technicianlocation_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='id_back_photo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='id_front_photo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='profile_photo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='selfie_with_id',
            field=models.TextField(blank=True),
        ),
    ]
