# Generated by Django 4.2.26 on 2025-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_jobposting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='technician_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
    ]
