# Generated by Django 4.2.26 on 2025-11-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_jobposting_payment_method_jobposting_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('stripe', 'Stripe (Card)'), ('paypal', 'PayPal')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('stripe', 'Stripe (Card)'), ('paypal', 'PayPal')], default='mpesa', max_length=20),
        ),
    ]
